Add-possibility-to-custom-timers
hifis-net/ansible-role-unattended-upgrades pull request #120
Opened 2023-05-31 14:24 UTC by pgassmann

Restore of !86 by @mabed-fr

2023-06-05 07:56 UTC, pgassmann commented
@christianhueserhzdr You reviewed the orignal PR from which I incorporated your feedback. Can you check the changes I did?

2023-06-05 12:13 UTC, Normo requested changes
Thank you very much @pgassmann! I made a few suggestions that should be implemented before we can merge it.

2023-06-05 12:13 UTC, Normo commented on tasks/systemd_timers.yml
> +  check_mode: 'no'
```suggestion
  check_mode: false
```

2023-06-05 12:13 UTC, Normo commented on tasks/systemd_timers.yml
> +  check_mode: 'no'
```suggestion
  check_mode: false
```

2023-06-05 12:13 UTC, Normo commented on tasks/systemd_timers.yml
> +    - '_apt_daily_upgrade_timer_d' # skip if run for the first  time in checkmode
```suggestion
    - '_apt_daily_upgrade_timer_d'  # skip if run for the first time in check mode
```

2023-06-05 12:13 UTC, Normo commented on tasks/systemd_timers.yml
> +    - '_apt_daily_timer_d' # skip if run for the first time in checkmode
```suggestion
    - '_apt_daily_timer_d'  # skip if run for the first time in check mode
```

2023-06-05 13:15 UTC, pgassmann commented on README.md
> +* Download is between 12:20am - 12:40am
this seems wrong to me. According to the docs, the RandomizedDelaySec should only be added.

2023-06-06 09:33 UTC, Normo commented on README.md
> +* Download daily between at random times during the entire day.
```suggestion
* Download daily at random times during the entire day.
```

2023-06-06 13:05 UTC, Normo commented on .github/workflows/ci.yml
> +        run: | # Compare with https://github.com/eriksjolund/user-systemd-service-actions-workflow/blob/efe872924fd2dd35bb482544126ce751303e14c2/README.md
```suggestion
        run: |  # Compare with https://github.com/eriksjolund/user-systemd-service-actions-workflow/blob/efe872924fd2dd35bb482544126ce751303e14c2/README.md
```

2023-06-06 13:10 UTC, Normo commented on tasks/systemd_timers.yml
> +    state: 'directory'
```suggestion
    state: 'directory'
    owner: 'root'
    group: 'root'
```

2023-06-06 13:10 UTC, Normo commented on tasks/systemd_timers.yml
> +    state: 'directory'
```suggestion
    state: 'directory'
    owner: 'root'
    group: 'root'
```

2023-06-06 13:11 UTC, Normo commented on tasks/systemd_timers.yml
> +    mode: '0644'
```suggestion
    mode: '0644'
    owner: 'root'
    group: 'root'
```

2023-06-06 13:11 UTC, Normo commented on tasks/systemd_timers.yml
> +    mode: '0644'
```suggestion
    mode: '0644'
    owner: 'root'
    group: 'root'
```

2023-06-06 13:13 UTC, Normo approved these changes
Thanks @pgassmann

2023-06-06 13:17 UTC, merged