Add possibility to custom timers  85
hifis-net/ansible-role-unattended-upgrades pull request #86
Opened 2023-01-22 10:41 UTC by mabed-fr

2023-01-25 15:19 UTC, mabed-fr commented
Hello

can i have a feedback ?

Mabed

2023-01-25 15:47 UTC, christianhueserhzdr commented
Dear Mathieu @mabed-fr, thank you very much for your contribution and creating a PR for this issue as well as adding yourself to the list of contributors with this PR. Since the change is an extensive one, we will put it on the agenda and try to review it in the next couple of days, so that you will get some feedback then. I hope this is fine with you. What I can see right now is that the CI jobs are failing. Do you see why this happens or do you need assistance with the CI output? Please let me know in this case. Thanks. With best regards, Christian

2023-01-25 16:39 UTC, mabed-fr commented
> Dear Mathieu @mabed-fr, thank you very much for your contribution and creating a PR for this issue as well as adding yourself to the list of contributors with this PR. Since the change is an extensive one, we will put it on the agenda and try to review it in the next couple of days, so that you will get some feedback then. I hope this is fine with you. What I can see right now is that the CI jobs are failing. Do you see why this happens or do you need assistance with the CI output? Please let me know in this case. Thanks. With best regards, Christian

No worries, with pleasure I really like unattended upgrade.

I tested under several OS on my side (Debian11, Debian10) and this is OK

CI output is too poor I need more detail if possible.

I may not be looking at the right output.

2023-01-26 10:35 UTC, christianhueserhzdr commented
> I fond error for all:
> 
> fatal: [instance]: FAILED! => {"changed": false, "checksum": "a66571bf380ad475ddd95516ea052d508360190c", "msg": "Destination directory /etc/systemd/system/apt-daily.timer.d does not exist"}
> 
> I search ...

Thanks, Mathieu @mabed-fr, for fixing the issue with the missing directories. Unfortunately, the change contains some unquotes strings, which leads to a failing linting stage in the CI pipeline. We also use Molecule in this project, hence you can test-run the CI pipeline also locally to spot these issues:

```
pip install -U pipenv
pipenv install --dev
pipenv run molecule test
```
I will now review your current PR and will write done some further suggestions.

2023-01-26 12:26 UTC, christianhueserhzdr requested changes
Dear Mathieu @mabed-fr, again, thank you very much for providing this PR and useful feature. All in all I think the implementation is a good one. There are small quality issues I think we need to tackle first. Please see my suggestions. If you need any assistance, please let me know. Thanks.

2023-01-26 12:26 UTC, christianhueserhzdr commented on README.md
> +Instalation is between 12:50am - 13:10
Small typo here:

```suggestion
Installation is between 12:50am - 13:10
```

2023-01-26 12:26 UTC, christianhueserhzdr commented on tasks/systemd_timers.yml
> +- name: 'Ensure apt-daily.timer.d exist'
```suggestion
- name: 'Ensure directory apt-daily.timer.d exist'
```

2023-01-26 12:26 UTC, christianhueserhzdr commented on tasks/systemd_timers.yml
> +- name: 'Ensure apt-daily-upgrade.timer.d'
```suggestion
- name: 'Ensure directory apt-daily-upgrade.timer.d'
```

2023-01-26 12:26 UTC, christianhueserhzdr commented on tasks/systemd_timers.yml
> +- name: 'Test apt-daily timer'
```suggestion
- name: 'Test apt-daily timer expression'
```

2023-01-26 12:26 UTC, christianhueserhzdr commented on tasks/systemd_timers.yml
> +- name: 'Test apt-daily-upgrade timer'
```suggestion
- name: 'Test apt-daily-upgrade timer expression'
```

2023-01-26 12:26 UTC, christianhueserhzdr commented on tasks/systemd_timers.yml
> +    - 'apt_daily_timer_d'
Would it be possible to make this condition more expressive?

2023-01-26 12:26 UTC, christianhueserhzdr commented on tasks/systemd_timers.yml
> +    - 'apt_daily_upgrade_timer_d'
Would it be possible to make this condition more expressive?

2023-01-26 12:26 UTC, christianhueserhzdr commented on README.md
> +Instalation is between 12:50am - 13:10
Small typo here:

```suggestion
Installation is between 12:50am - 13:10
```

2023-01-26 12:26 UTC, christianhueserhzdr commented on tasks/systemd_timers.yml
> +    path: /etc/systemd/system/apt-daily.timer.d
Quotes missing:

```suggestion
    path: '/etc/systemd/system/apt-daily.timer.d'
```

2023-01-26 12:26 UTC, christianhueserhzdr commented on tasks/systemd_timers.yml
> +    state: directory
Quotes missing:

```suggestion
    state: 'directory'
```

2023-01-26 12:26 UTC, christianhueserhzdr commented on tasks/systemd_timers.yml
> +    path: /etc/systemd/system/apt-daily-upgrade.timer.d
Quotes missing:

```suggestion
    path: '/etc/systemd/system/apt-daily-upgrade.timer.d'
```

2023-01-26 12:26 UTC, christianhueserhzdr commented on tasks/systemd_timers.yml
> +    state: directory
Quotes missing:

```suggestion
    state: 'directory'
```

2023-01-26 12:26 UTC, christianhueserhzdr commented on tasks/systemd_timers.yml
> +    mode: 0644
Quotes would make sense here as well:

```suggestion
    mode: '0644'
```

2023-01-26 12:26 UTC, christianhueserhzdr commented on tasks/systemd_timers.yml
> +    mode: 0644
Quotes would make sense here as well:

```suggestion
    mode: '0644'
```

2023-01-26 19:04 UTC, mabed-fr commented
`yaml[quoted-strings]: String value is not quoted with any quotes
tasks/systemd_timers.yml:19

yaml[quoted-strings]: String value is not quoted with any quotes
tasks/systemd_timers.yml:21

yaml[quoted-strings]: String value is not quoted with any quotes
tasks/systemd_timers.yml:26

yaml[quoted-strings]: String value is not quoted with any quotes
tasks/systemd_timers.yml:28`

2023-01-27 10:16 UTC, christianhueserhzdr commented
> I think it's good now.

Thanks, Mathieu @mabed-fr, for fixing those linting issues reported in the pipeline. The pipeline runs smoothly, yes. That's a good first step that the deployment works fine. Now, I would like to ask you to take also the other review suggestions into account. It would be great if every suggestion is at least answered or even implemented. Thank you very much! And have a fabulous weekend.

2023-01-27 12:41 UTC, mabed-fr commented on templates/apt_daily_override.conf.j2
> +OnCalendar=
Yes because we are forced to reset the calendar, and this is the official method

2023-01-27 12:42 UTC, mabed-fr commented on README.md
> +Install 7/7 between 5am - 7pm
7 days / 7 days

2023-01-27 12:42 UTC, mabed-fr commented on README.md
> +Donwload 7/7 between at 6am AND 6pm
7 days / 7 days

2023-01-27 12:56 UTC, mabed-fr commented on templates/apt_daily_upgrade_override.conf.j2
> +[Install]
Yes

2023-01-27 12:56 UTC, mabed-fr commented on tasks/systemd_timers.yml
> +    dest: '/etc/systemd/system/apt-daily.timer.d/override.conf'
Is the name when launch systemd edit apt-daily.timer

2023-01-31 19:41 UTC, closed without merging