Test the role via molecule
hifis-net/ansible-role-unattended-upgrades pull request #9
Opened 2022-08-16 11:45 UTC by tobiashuste

* Manage dependencies via pipenv
* Run Molecule via GitHub Actions

Closes #8

2022-08-16 13:30 UTC, tobiashuste commented
@Normo I would be happy if you could have a look. This implements basic role testing via molecule. There is no verification step implemented yet. It simply takes the default installation and deploys it in one of the container.

2022-08-17 06:03 UTC, Normo requested changes
Thank you very much @tobiashuste for implementing this! :star_struck: Very much appreciate the effort. I've added some comments/suggestions.

2022-08-17 06:04 UTC, Normo commented on .github/workflows/ci.yml
> +      - "main"
What do you think @tobiashuste ? Shall we rename the default branch to `main`?

2022-08-18 05:04 UTC, Normo commented
@tobiashuste We can take inspiration for the verfication step from the test play in [tests/test.yml](https://github.com/hifis-net/ansible-role-unattended-upgrades/blob/master/tests/test.yml#L28)

2022-08-18 05:21 UTC, tobiashuste commented on .github/workflows/ci.yml
> +      - "main"
Probably we should do this.

2022-08-18 05:56 UTC, tobiashuste commented
> @tobiashuste We can take inspiration for the verfication step from the test play in [tests/test.yml](https://github.com/hifis-net/ansible-role-unattended-upgrades/blob/master/tests/test.yml#L28)

@Normo I implemented the verification step according to the existing tests. I also changed your other suggestions.

So far I did not touch the branch name to wait for your feedback.

2022-08-18 06:36 UTC, Normo commented on .github/workflows/ci.yml
> +      - "main"
:ok_hand: let's do it with #13

2022-08-18 06:52 UTC, Normo approved these changes
Thanks, @tobiashuste LGTM :+1:

2022-08-18 06:53 UTC, merged